We are tracking two players in a basketball game. We're given the following information:

Kevin scored 4/10 of his shots in the first half, and 3/4 of his shots in the second half
Kobe scored 1/4 of his shots in the first half, and 7/10 of his shots in the second half



` What is Kevin's performance overall? `

In [1]:
7/14

0.5

` What is Kobe's performance overall? `

In [2]:
8/14

0.5714285714285714

## Airline Problem

In [6]:
def calculate_ontime(arrivals, ontime_pct):
    ontime = arrivals * ontime_pct
    delayed = arrivals - ontime
    return (ontime, delayed)

In [11]:
calculate_ontime(2146, 0.858)

(1841.268, 304.73199999999997)

In [12]:
(497 + 221 + 212 + 503 + 1841) / 3775

0.8672847682119206

In [17]:
calculate_ontime(262, 0.767)

(200.954, 61.04599999999999)

In [18]:
(694 + 4840 + 383 + 320 + 201) / 7225

0.8910726643598615

## Array Manipulation using Numpy

In [20]:
import numpy as np

X = np.array(
[[73.847017017515, 241.893563180437],
 [68.7819040458903, 162.3104725213],
 [74.1101053917849, 212.7408555565],
 [71.7309784033377, 220.042470303077],
 [69.8817958611153, 206.349800623871],
 [67.2530156878065, 152.212155757083],
 [68.7850812516616, 183.927888604031],
 [68.3485155115879, 167.971110489509],
 [67.018949662883, 175.92944039571],
 [63.4564939783664, 156.399676387112]]
)

In [23]:
X.shape

(10, 2)

In [25]:
print(X[:, 0])

[73.84701702 68.78190405 74.11010539 71.7309784  69.88179586 67.25301569
 68.78508125 68.34851551 67.01894966 63.45649398]


In [27]:
np.mean(X[:, 0])

69.32138568119487

In [31]:
np.mean(X[:, 1])

187.97774338186304

In [37]:
np.mean(X, axis=0)

array([ 69.32138568, 187.97774338])

In [41]:
np.mean(X[:5, 1])

208.667432437037

In [44]:
np.mean(X[8, 0])

67.018949662883

In [46]:
X - np.mean(X, axis=0)

array([[  4.52563134,  53.9158198 ],
       [ -0.53948164, -25.66727086],
       [  4.78871971,  24.76311217],
       [  2.40959272,  32.06472692],
       [  0.56041018,  18.37205724],
       [ -2.06836999, -35.76558762],
       [ -0.53630443,  -4.04985478],
       [ -0.97287017, -20.00663289],
       [ -2.30243602, -12.04830299],
       [ -5.8648917 , -31.57806699]])

In [49]:
A = np.array([[1,2], [3,4]])

In [54]:
print(A)
print(np.sum(A))
print(np.sum(A, axis=0))
print(np.sum(A, axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [56]:
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [58]:
print(A.shape)

(4, 3)


In [62]:
B = A.reshape(2, 6)
print(B)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [65]:
(1 * 0.166) + (2 * 0.166) + (3 * 0.166) + (4 * 0.166) + (5 * 0.166) + (6 * 0.166)

3.486

In [119]:
dice = np.random.randint(low=1.0, high=7.0, size=1000)
print(np.mean(dice))

3.471
