In [2]:
import numpy as np

In [7]:
A = np.array([[1, 2], [0, 1], [2, 3]])
v = np.array([[2], [6]])
print(A)
print(v)
print(np.dot(A, v))

[[1 2]
 [0 1]
 [2 3]]
[[2]
 [6]]
[[14]
 [ 6]
 [22]]


In [9]:
A = np.array([[1, 2], [0, 1], [2, 3]])
v = np.array([[5], [7]])
print(A)
print(v)
print(np.dot(A, v))

[[1 2]
 [0 1]
 [2 3]]
[[5]
 [7]]
[[19]
 [ 7]
 [31]]


In [11]:
A = np.array([[1, 2], [0, 1], [2, 3]])
B = np.array([[2, 5], [6, 7]])
print(A)
print(B)
print(np.dot(A, B))

[[1 2]
 [0 1]
 [2 3]]
[[2 5]
 [6 7]]
[[14 19]
 [ 6  7]
 [22 31]]


In [13]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
print(A.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [19]:
A2 = np.transpose(A)
print(A2)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [22]:
print(np.dot(A, A2))

[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]


In [24]:
print(np.dot(A2, A))

[[ 66  78  90]
 [ 78  93 108]
 [ 90 108 126]]


In [28]:
C = np.ones((3, 3))
print(C)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [38]:
from numpy import linalg as LA
v = np.array([3, 4])
LA.norm(v)

5.0

In [43]:
print(np.sqrt(np.dot(v, v.T)))

5.0


In [48]:
u = np.array([1, 1])
v = np.array([2, 2])
r = np.array([3, 8])
print(LA.norm(u - v))
print(LA.norm(u - r))
print(LA.norm(v - r))

1.4142135623730951
7.280109889280518
6.082762530298219
